name: FreeTV

on:
  schedule:
   - cron: '0 */1 * * *'
    
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          pip3 install -r code/requirements.txt
      - name: execute py script 
        run: python code/main.py input/config.json
      - name: commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated streams"
          git push
